import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Geist, Inter, Manrope, Montserrat, Poppins } from "next/font/google";
import { cn } from "@/lib/utils";

import { TrpcProvider } from "@/context/trpc/trpcProvider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
})

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-manrope',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font--poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(`${poppins.className} font-sans` )}>
      <body className={`    scroll-smooth bg-[#0A0A0C] text-white`}>
        <TrpcProvider>
              {children}
        </TrpcProvider>
        

      </body>
    </html>
  );
}
