/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { createMessageSchema, messageSchema, messageQuerySchema, infiniteMessageSchema, createToggleConversationRequestSchema } from "../conversations/schema/conversation.zod.schema";
import { createPostSchema, postSchema, postPaginationQuerySchema, postInfiniteScrollSchemaQuery, savedPostInfiniteScrollSchema, createCommentSchema, commentSchema, commentPaginationQuerySchema, commentInfiniteScrollSchema } from "../post/schema/post.zod.schema";
import { UserSchema, UserProfileQuerySchema, UserPaginationQuerySchema, FollowersInfiniteScrollSchema, usersInfiniteScrollSchema, FollowingInfiniteScrollSchema, storySchema, addStorySchema } from "../user/schema/user.zod.schema";

const appRouter = t.router({
  conversation: t.router({
    sendMessage: publicProcedure
      .input(createMessageSchema)
      .output(messageSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getInfiniteMessages: publicProcedure
      .input(messageQuerySchema)
      .output(infiniteMessageSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    toggleConversationRequest: publicProcedure
      .input(createToggleConversationRequestSchema)
      .output(z.boolean().nullable().optional())
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  post: t.router({
    createPost: publicProcedure
      .input(createPostSchema)
      .output(postSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getAllPost: publicProcedure
      .input(postPaginationQuerySchema)
      .output(postInfiniteScrollSchemaQuery)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getSavedPosts: publicProcedure
      .input(postPaginationQuerySchema)
      .output(savedPostInfiniteScrollSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    toggleLike: publicProcedure
      .input(z.object({
            postId:z.string()
        }))
      .output(z.object({
            liked:z.boolean()
        }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    toggleSave: publicProcedure
      .input(z.object({
            postId:z.string()
        }))
      .output(z.object({
            savedPost:z.boolean()
        }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createComment: publicProcedure
      .input(createCommentSchema)
      .output(commentSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    toggleCommentlike: publicProcedure
      .input(z.object({
            commentId:z.string()
        }))
      .output(z.object({
            liked:z.boolean()
        }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getInfinteComment: publicProcedure
      .input(commentPaginationQuerySchema)
      .output(commentInfiniteScrollSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    deleteComment: publicProcedure
      .input(z.object({
            postId:z.string()
        }))
      .output(z.void())
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  user: t.router({
    getUserById: publicProcedure
      .input(z.object({
            userId:z.string()
        }))
      .output(UserSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    editProfile: publicProcedure
      .input(UserProfileQuerySchema)
      .output(z.object({
            id:z.string()
        }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    toggleFollow: publicProcedure
      .input(z.object({
            targetUserId:z.string()
        }))
      .output(z.object({
            isFollowing:z.boolean()
        }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getInfiniteFollowers: publicProcedure
      .input(UserPaginationQuerySchema)
      .output(FollowersInfiniteScrollSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getInfiniteUsersToFollow: publicProcedure
      .input(UserPaginationQuerySchema)
      .output(usersInfiniteScrollSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getInfiniteFollowing: publicProcedure
      .input(UserPaginationQuerySchema)
      .output(FollowingInfiniteScrollSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getStories: publicProcedure
      .output(z.array(storySchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    addStory: publicProcedure
      .input(addStorySchema)
      .output(storySchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
